[package]
name = "phylotree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
itertools = "0.10.5"
pest = "2.5.7"
pest_derive = "2.5.7"
ptree = "0.4.0"
rand = "0.8.5"
thiserror = "1.0.40"
utf8-read = "0.4.0"
